<?php

namespace ContainerMWSLiAg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PK5KVtZService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.PK5KVtZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PK5KVtZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comment' => ['privates', '.errored..service_locator.PK5KVtZ.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.PK5KVtZ": it references class "App\\Entity\\Comment" but no such service exists.'],
        ], [
            'comment' => 'App\\Entity\\Comment',
        ]);
    }
}
