<?php

namespace ContainerMWSLiAg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UB6m8znService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.UB6m8zn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UB6m8zn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tag' => ['privates', '.errored..service_locator.UB6m8zn.App\\Entity\\Tag', NULL, 'Cannot autowire service ".service_locator.UB6m8zn": it references class "App\\Entity\\Tag" but no such service exists.'],
        ], [
            'tag' => 'App\\Entity\\Tag',
        ]);
    }
}
