<?php

namespace ContainerMWSLiAg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.NyLbAvG.App\Entity\Article' shared service.
     *
     * @return \App\Entity\Article
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.NyLbAvG": it references class "App\\Entity\\Article" but no such service exists.');
    }
}
