<?php

namespace ContainerMWSLiAg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGregwarCaptcha_CaptchaBuilderService extends App_KernelProdContainer
{
    /*
     * Gets the public 'gregwar_captcha.captcha_builder' shared service.
     *
     * @return \Gregwar\Captcha\CaptchaBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['gregwar_captcha.captcha_builder'] = new \Gregwar\Captcha\CaptchaBuilder();
    }
}
