<?php

namespace ContainerMWSLiAg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLinkService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.oQOitD_.App\Entity\Link' shared service.
     *
     * @return \App\Entity\Link
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.oQOitD_": it references class "App\\Entity\\Link" but no such service exists.');
    }
}
