<?php

namespace ContainerMWSLiAg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SearchController' shared autowired service.
     *
     * @return \App\Controller\SearchController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SearchController'] = $instance = new \App\Controller\SearchController();

        $instance->setContainer(($container->privates['.service_locator.0ghLsew'] ?? $container->load('get_ServiceLocator_0ghLsewService'))->withContext('App\\Controller\\SearchController', $container));

        return $instance;
    }
}
