<?php

namespace ContainerMWSLiAg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTag2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.WGpE457.App\Entity\Tag' shared service.
     *
     * @return \App\Entity\Tag
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.WGpE457": it references class "App\\Entity\\Tag" but no such service exists.');
    }
}
