<?php

namespace ContainerOGzeC30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OQOitDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oQOitD_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oQOitD_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'link' => ['privates', '.errored..service_locator.oQOitD_.App\\Entity\\Link', NULL, 'Cannot autowire service ".service_locator.oQOitD_": it references class "App\\Entity\\Link" but no such service exists.'],
        ], [
            'link' => 'App\\Entity\\Link',
        ]);
    }
}
