<?php

namespace ContainerOGzeC30;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PK5KVtZ.App\Entity\Comment' shared service.
     *
     * @return \App\Entity\Comment
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PK5KVtZ": it references class "App\\Entity\\Comment" but no such service exists.');
    }
}
