<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMWSLiAg\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMWSLiAg/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerMWSLiAg.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerMWSLiAg\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerMWSLiAg\App_KernelProdContainer([
    'container.build_hash' => 'MWSLiAg',
    'container.build_id' => '3958efd7',
    'container.build_time' => 1677616012,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMWSLiAg');
