<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOGzeC30\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOGzeC30/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOGzeC30.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOGzeC30\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOGzeC30\App_KernelDevDebugContainer([
    'container.build_hash' => 'OGzeC30',
    'container.build_id' => '4350e3aa',
    'container.build_time' => 1677353552,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOGzeC30');
